title: Prasanth Ananth
description: Portfolio of engineering R&D projects
theme: jekyll-theme-cayman
google_analytics: G-T8PW6PT0R4
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - robotics.md